apiVersion: network.awsblueprints.io/v1alpha1
kind: amazonVpc
metadata:
  name: xplane-amazon-vpc
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      awsblueprints.io/provider: aws
      awsblueprints.io/environment: dev
      service: vpc
      compute: managedamazon-vpc
  resourceConfig:
    providerConfigName: aws-provider-config
    region: us-east-1
  parameters:
    vpcName: aws-provider-vpc
    vpccidrBlock: "10.20.0.0/16"
    amazonProvidedIpv6CidrBlock: true